@startuml C4_Component
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(container2Alias, "ToDo List - Java Spring Boot Backend") {
Component(component1Alias, "Controller", "Spring MVC Rest Controller", "Gerencia solicitações de API do ToDo List ")
Component(component2Alias, "Service", "Spring Service", "Gerencia a lógica de negócio do ToDo List")
Component(component3Alias, "Repository", "Spring Data JPA Repository", "Gerencia o acesso aos dados do ToDo List")
}

Rel(component1Alias, component2Alias, "Chama")
Rel(component2Alias, component3Alias, "Utiliza")

@enduml